<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.groceryadmin.automation</groupId>
	<artifactId>grocery-adminpanel-automation-framework</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>GroceryStoreSeleniumAutomationFramework</name>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.1.2</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>testng.xml</suiteXmlFile>
					</suiteXmlFiles>
					<systemPropertyVariables>
						<headless>${headless}</headless>
						<!--<browser>${browser}</browser>bridges -Dbrowser from the outer mvn process into the forked test JVM. reference for what command-line override would look like-->
					</systemPropertyVariables>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<properties>
		<headless>false</headless>
		<!--<browser>chrome</browser> browser value fetched by deafult if -Dbrowser is not passed in cmd, My cross-browser suite intentionally uses three different browser values across three blocks in one suite file, so a global -Dbrowser override would silently collapse all three to just one browser, defeating the suite's purpose
		Surefire forks a separate JVM for tests, which does not inherit -D flags from the outer `mvn`process unless systemPropertyVariables explicitly bridges them, that is it can't fetch from parameter tags in suite xml files but need a separate properties tag in pom since it can only fetch pom level values
		-->
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.13.0</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.2</version>
		</dependency>
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.0.9</version>
		</dependency>
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>6.3.4</version>
		</dependency>
		<dependency>
			<groupId>com.github.javafaker</groupId>
			<artifactId>javafaker</artifactId>
			<version>1.0.2</version>
		</dependency>
	</dependencies>
</project>